apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "domaudit.fullname" . }}
  labels:
    {{- include "domaudit.labels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.config.compute_namespace }}
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.config.platform_namespace }}
    ports:
    - protocol: TCP
      port: {{ int .Values.config.port }}
    - protocol: TCP
      port: {{ int .Values.ui.config.port }}
  podSelector: 
    matchLabels:
      {{- include "domaudit.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress